version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_1
    env_file:
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d TrueCodeTask"]
      interval: 5s
      timeout: 5s
      retries: 5

  nest-app:
    build: .
    container_name: nest_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - app_network

networks:
  app_network: